export default [
  {
    imageSrc: "../../../../../mostPopularItems/inv.jpg",
    description: `DUALCOOL Inverter AC, 2.5HP, 10 Year Warranty, 70% Energy Saving,
        40% Faster Cooling`,
    rating: 0,
    quantity: 0,
    id: 0,
    alt: " ac inverter",
  },
  {
    imageSrc: "../../../../../mostPopularItems/tv-1.jpg",
    description: `LG UHD 4K TV 43 Inch UN70 Series, 4K UHD Smart TV`,
    rating: 0,
    quantity: 0,
    id: 1,
    alt: "tv ",
  },
  {
    imageSrc: "../../../../../mostPopularItems/LHD.jpg",
    description: `1000W4.2CH HOME THEATRE SYSTEM, DUAL SUBWOOFER, AUX IN, USB DIRECT RECORDING`,
    rating: 5,
    quantity: 1,
    id: 2,
    alt: " home theatre",
  },
  {
    imageSrc: "../../../../../mostPopularItems/oven-1.jpg",
    description: `Microwave Oven, 25litres, Black, Smart Inverter with 10year warranty, Smart Auto Cook, Full Glass Touch/Dual Control, LED Lighting`,
    rating: 1,
    quantity: 1,
    id: 3,
    alt: " microwave oven",
  },
  {
    imageSrc: "../../../../../mostPopularItems/LHT-1.jpg",
    description: `LG Home Theater LHD687`,
    rating: 0,
    quantity: 1,
    id: 4,
    alt: "home theatre ",
  },
  {
    imageSrc: "../../../../../mostPopularItems/LHD-2.jpg",
    description: `1000W 5.1CH HOME THEATRE SYSTEM , JERSEY SPEAKER, 4 TALLBOY, FRONT FIRING SUBWOOFER`,
    rating: 4.5,
    quantity: 2,
    id: 5,
    alt: " home theatre",
  },
  {
    imageSrc: "../../../../../mostPopularItems/Basic_350.jpg",
    description: `659L InstaView™ Door-in-Door® Refrigerator with Inverter Linear Compressor`,
    rating: 0,
    quantity: 0,
    id: 6,
    alt: "refrigerator ",
  },

  {
    imageSrc: "../../../../../mostPopularItems/Basic-350.jpg",
    description: `LG LED Smart TV 43 inch LM6300 Series Full HD HDR Smart LED TV`,
    rating: 0,
    quantity: 0,
    id: 7,
    alt: " tv ",
  },
  {
    imageSrc: "../../../../../mostPopularItems/TV-2.jpg",
    description: `LG NanoCell TV 75 Inch NANO97 Series, Cinema Screen Design 8K Cinema HDR WebOS Smart AI ThinQ Full Array Dimming`,
    rating: 5,
    quantity: 1,
    id: 8,
    alt: "tv ",
  },
];
