export default [
  {
    imageSrc: "../../../../../newOffers/350h.jpg",
    description: `950W, Mini Audio, Multi Color lighting, Karaoke Star, Multi Bluetooth`,
    rating: 5,
    quantity: 3,
    id: 0,
    alt: "speaker",
  },
  {
    imageSrc: "../../../../../newOffers/350-2.jpg",
    description: `LG UHD 4K TV 43 Inch UN70 Series, 4K UHD Smart TV`,
    rating: 0,
    quantity: 0,
    id: 1,
    alt: "tv",
  },
  {
    imageSrc: "../../../../../newOffers/tv-1.jpg",
    description: `LG LED TV 43 inch LM5000 Series Full HD LED TV`,
    rating: 5,
    quantity: 1,
    id: 2,
    alt: "tv",
  },
  {
    imageSrc: "../../../../../newOffers/TH-350.jpg",
    description: `889L, InstaView Door in Door with Dispenser,  HygieneFresh+™, Inverter Linear Compressor`,
    rating: 5,
    quantity: 2,
    id: 3,
    alt: "dispenser",
  },
  {
    imageSrc: "../../../../../newOffers/350g.jpg",
    description: `LG UHD 4K TV 82 Inch UN80 Series, Cinema Screen Design 4K Active HDR WebOS Smart AI ThinQ`,
    rating: 0,
    quantity: 0,
    id: 4,
    alt: "tv",
  },
  {
    imageSrc: "../../../../../newOffers/350_th.jpg",
    description: `6kg / White, Twin Tub Washer,Roller Jet, Wind Jet, 3 Wash Program`,
    rating: 5,
    quantity: 2,
    id: 5,
    alt: "tub washer",
  },
  {
    imageSrc: "../../../../../newOffers/350t.jpg",
    description: `8.0kg, Plastic Body, Roller Jet Pulsator, Collor Scubber, Soak, Dark Blue`,
    rating: 0,
    quantity: 0,
    id: 6,
    alt: "tub washer",
  },
  {
    imageSrc: "../../../../../newOffers/inv.jpg",
    description: `DUALCOOL Inverter AC,2.5HP, 10 Year Warranty,70% Energy Saving, 40% Faster Cooling`,
    rating: 0,
    quantity: 0,
    id: 7,
    alt: "ac",
  },
  {
    imageSrc: "../../../../../newOffers/brownTv.jpg",
    description: `6kg / White, Twin Tub Washer,Roller Jet, Wind Jet, 3 Wash Program`,
    rating: 5,
    quantity: 2,
    id: 8,
    alt: "tv",
  },
];
