export default [
  {
    imageSrc: "../../../../../newest/350t.jpg",
    description: `8.0kg, Plastic Body, Roller Jet Pulsator, Collor Scubber, Soak, Dark Blue`,
    rating: 0,
    quantity: 0,
    id: 0,
    alt: "tub washer",
  },
  {
    imageSrc: "../../../../../newest/350g.jpg",
    description: `LG UHD 4K TV 82 Inch UN80 Series, Cinema Screen Design 4K Active HDR WebOS Smart AI ThinQ`,
    rating: 0,
    quantity: 0,
    id: 1,
    alt: "tv",
  },
  {
    imageSrc: "../../../../../newest/TH-350.jpg",
    description: `889L, InstaView Door in Door with Dispenser,  HygieneFresh+™, Inverter Linear Compressor`,
    rating: 5,
    quantity: 2,
    id: 2,
    alt: "dispenser",
  },
  {
    imageSrc: "../../../../../newest/350rr.jpg",
    description: `LG LED TV 43 inch LM5000 Series Full HD LED TV`,
    rating: 5,
    quantity: 3,
    id: 3,
    alt: "tv",
  },
  {
    imageSrc: "../../../../../newest/350rr.jpg",
    description: `LG LED TV 32 inch LM5000 Series Full HD LED TV`,
    rating: 5,
    quantity: 1,
    id: 4,
    alt: "tv",
  },
  {
    imageSrc: "../../../../../newest/boom.jpg",
    description: `LG XBOOMGo PL7`,
    rating: 0,
    quantity: 0,
    id: 5,
    alt: "boom player",
  },
  {
    imageSrc: "../../../../../newest/Thumb_350.jpg",
    description: `LG XBOOMGo PL5`,
    rating: 0,
    quantity: 0,
    id: 6,
    alt: "boom player",
  },
  {
    imageSrc: "../../../../../newest/Basic-350t.jpg",
    description: `LG XBOOM ON`,
    rating: 0,
    quantity: 0,
    id: 7,
    alt: "boom player",
  },
  {
    imageSrc: "../../../../../newest/xBoom.jpg",
    description: `LG XBOOM ON9`,
    rating: 0,
    quantity: 0,
    id: 8,
    alt: "boom player",
  },
];
