export default [
  {
    imageSrc: "../../../../../highlyRated/350r.jpg",
    description: `950W, Mini Audio, Multi Color lighting, Karaoke Star, Multi Bluetooth`,
    rating: 5,
    quantity: 3,
    id: 0,
    alt: "mini audio",
  },
  {
    imageSrc: "../../../../../highlyRated/TH-350.jpg",
    description: `889L, InstaView Door in Door with Dispenser,  HygieneFresh+™, Inverter Linear Compressor`,
    rating: 5,
    quantity: 2,
    id: 1,
    alt: "dispenser",
  },
  {
    imageSrc: "../../../../../highlyRated/brownTv.jpg",
    description: `LG UHD TV 50 inch UM7340 Series 4K Display 4K HDR Smart LED TV w/ ThinQ AI`,
    rating: 5,
    quantity: 2,
    id: 2,
    alt: "Tv",
  },

  {
    imageSrc: "../../../../../highlyRated/350_th.jpg",
    description: `6kg / White, Twin Tub Washer,Roller Jet, Wind Jet, 3 Wash Program`,
    rating: 5,
    quantity: 2,
    id: 3,
    alt: "tub washer",
  },
  {
    imageSrc: "../../../../../highlyRated/350h.jpg",
    description: `40W Mini Audio, USB, SD Card, Portable In`,
    rating: 5,
    quantity: 2,
    id: 4,
    alt: "Tv",
  },
  {
    imageSrc: "../../../../../highlyRated/350-2.jpg",
    description: `40W Mini Audio, USB, SD Card, Portable In`,
    rating: 5,
    quantity: 1,
    id: 5,
    alt: "Tv",
  },
  {
    imageSrc: "../../../../../highlyRated/350-2.jpg",
    description: `LG LED TV 32 inch LM5000 Series Full HD LED TV`,
    rating: 5,
    quantity: 1,
    id: 6,
    alt: "Tv",
  },
  {
    imageSrc: "../../../../../highlyRated/basic-350.jpg",
    description: `LG UHD 4K TV 60 Inch UN71 Series, 4K Active HDR WebOS Smart AI ThinQ`,
    rating: 5,
    quantity: 1,
    id: 7,
    alt: "Tv",
  },
  {
    imageSrc: "../../../../../highlyRated/350-2.jpg",
    description: `LG UHD 4K TV 50 Inch UN73 Series, 4K Active HDR WebOS Smart AI ThinQ`,
    rating: 5,
    quantity: 1,
    id: 8,
    alt: "Tv",
  },
  {
    imageSrc: "../../../../../highlyRated/350_new.jpg",
    description: `65UN7440PVA`,
    rating: 5,
    quantity: 1,
    id: 9,
    alt: "Tv",
  },
];
